apiVersion: apps/v1
kind: Deployment
metadata:
  name: cifar-api-deployment 
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: cifar-api 
  template: 
    metadata:
      labels:
        app: cifar-api 
    spec:
      containers:
      - name: cifar-api-container 
        image: keremkartal1717/cifar-api:0.1 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000 